### ISSUE TITLE
DNS Over HTTPS V4 experiment is not removed after its expiration date

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [jonathanKingston/http-dns#26] opened 2018-09-10 08:27 UTC
[Affected versions]:
- Beta 63.0b4
- DNS Over HTTPS V4 

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- "network.trr.uri" pref is set to "https://mozilla.cloudflare-dns.com/dns-query"
- DNS Over HTTPS V4 .xpi is installed ([link](https://bugzilla.mozilla.org/show_bug.cgi?id=1485398#c42)). 

[Steps to reproduce]:
1. Set the system date to 3 weeks after the current date.
2. Open the browser with the profile from prerequisites and navigate to "about:addons">Extensions section.
3. Observe the add-ons section. 

[Expected result]:
- DNS Over HTTPS V4 experiment is uninstalled and no longer displayed in the add-ons section.

[Actual result]:
- DNS Over HTTPS V4 experiment remains installed and displayed in the add-ons section.

[Notes]:
- Added a screen recording with the issue:

![expire](https://user-images.githubusercontent.com/26000308/45285364-aeeecd00-b4eb-11e8-8282-587d4f6491fc.gif)

**Comment by jonathanKingston** [comment] 2018-09-10 09:00
Fixed with: https://github.com/jonathanKingston/http-dns/pull/25

**Closed as completed by jonathanKingston** 2018-09-10 09:00 UTC

**Comment by Softvision-RemusDranca** [comment] 2018-09-10 16:19
I have verified this issue using the latest DNS Over HTTPS V4 (4.0.4-signed) version and the issue is no longer reproducible. Tested on Windows 10 x64, Mac 10.13 and Ubuntu 16.04 x64.
