### ISSUE TITLE
The telemetry pings are no longer triggered if the value of the "network.trr.experimentalPerfInterval" pref is changed

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [jonathanKingston/http-dns#39] opened 2019-03-21 15:02 UTC
[Affected versions]:
- Firefox Release 66.0 Unbranded build

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- The DNS Over HTTPS v6 custom build is installed.
- The DNS study is already enabled.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to "about:config" page and search for the "network.trr.experimentalPerfInterval" pref.
3. Change the pref value to 60000 (1 minute).
4. Restart the browser.
5. Wait a minute and navigate to "about:telemetry" page.
6. Observe the shield study-add-on pings.

[Expected result]:
- New pings are triggered after each minute. 

[Actual result]:
- No new pings are triggered.

[Notes]:
- The issue is also reproducible if you change the pref to 12000 (2 minutes) or 300000 (5 minutes).

**Comment by jonathanKingston** [comment] 2019-03-28 19:10
This seems like a broken build can you retest with the latest signed addon please?

**Comment by Softvision-PatriciuPop** [comment] 2019-04-01 14:23
@jonathanKingston Tested this scenario using the latest build of DNS Over HTTPS (6.0.3) on Unbranded Firefox 66.0.2 and the issue is still reproducible.
There was no performance ping observed in "about:telemetry" page nor in the folder of the local server we set for testing purpose.

**Comment by jonathanKingston** [comment] 2019-04-01 15:14
@Softvision-PatriciuPop Is the addon still installed? It removes itself if some of the prefs have been modified already.
Was there any output in the browser toolbox?

I refreshed the telemetry page and can see reports every minute still:
![Screenshot from 2019-04-01 16-13-24](https://user-images.githubusercontent.com/338988/55338692-26d91080-5499-11e9-9e09-0b943a9127f7.png)

**Comment by Softvision-PatriciuPop** [comment] 2019-04-01 15:56
It appears that restarting the browser causes this behavior as stated in issue [41](https://github.com/jonathanKingston/http-dns/issues/41).

**Comment by jonathanKingston** [comment] 2019-04-01 16:24
Closing in favour of #41

**Closed as completed by jonathanKingston** 2019-04-01 16:24 UTC
