### ISSUE TITLE
DNS Over HTTPS V4 is uninstalled after restarting the browser

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [jonathanKingston/http-dns#24] opened 2018-09-07 12:32 UTC
[Notes]:
- This is only reproducible with the "active" branch of the study.

[Affected versions]:
- Firefox Beta 63.0b3
- DNS Over HTTPS V4

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- "network.trr.uri" pref is set to "https://mozilla.cloudflare-dns.com/dns-query"
- DNS Over HTTPS V4 . (4.0.2)add-on is available ([link](https://bugzilla.mozilla.org/show_bug.cgi?id=1485398)).

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to the "about:addons" page -> Extensions section.
3. Drag and drop the DNS Over HTTPS V4 add-on into the Extensions section.
4. Click "OK, Got it" button from the banner.
5. Restart the browser and observe if DNS experiment is still displayed in Add-ons Manager.

[Expected result]:
- The DNS Over HTTPS V4 experiment is still enabled and displayed. 

[Actual result]:
- The DNS Over HTTPS V4 experiment is no longer enabled and displayed. 

[Additional Notes]:
- The experiment is also gone from "about:support" page.
- These are the errors from the Browser console after reopening the browser:

```
Bootstrapped manifest not allowed to use 'resource' directive. chrome.manifest:2
Cannot send function call result: other side closed connection (call data: ({path:"experiments.settings.clear", args:[{shouldUninstall:true, urls:[], endingName:"ineligible", queryArgs:{shield:3, study:"httpdns@shield.mozilla.org", variation:"trr-active", updateChannel:"beta", fxVersion:"63.0", addon:"4.0.1", who:"6c7b5f06-7162-4a6e-83b2-8168fc067c03", testing:1, reason:"ineligible", fullreason:"ineligible"}}]}))
Ignoring response to aborted listener for 22
Error: endStudy, requested:  user-disable, but already ending ineligible ExtensionUtils.jsm:48:49
1536332811140 addons.xpi WARN Attempted to remove httpdns@shield.mozilla.org from app-profile but it was already gone
Key event not available on some keyboard layouts: key=“r” modifiers=“accel,alt” id=“key_toggleReaderMode” browser.xul
Key event not available on some keyboard layouts: key=“i” modifiers=“accel,alt,shift” id=“key_browserToolbox” browser.xul
1536332870351 Toolkit.Telemetry WARN TelemetryStorage::_scanArchive - have seen this id before: 671d5594-7069-46b9-84ee-714e9dcab325, overwrite: false
1536332870351 Toolkit.Telemetry WARN TelemetryStorage::_scanArchive - have seen this id before: 33fcae86-f48a-4c5a-b136-61436ce54061, overwrite: false
1536332870351 Toolkit.Telemetry WARN TelemetryStorage::_scanArchive - have seen this id before: fdd2a6b2-80a2-4420-93dd-7d5a51a4dc2c, overwrite: false
1536332870351 Toolkit.Telemetry WARN TelemetryStorage::_scanArchive - have seen this id before: 8aac80d7-99be-4e0b-a1dc-1f97ba9cdc1b, overwrite: false
1536332870352 Toolkit.Telemetry WARN TelemetryStorage::_scanArchive - have seen this id before: 9e3d507a-e707-471e-ac8c-798c3d91e314, overwrite: false
```

- Added a screen recording with the issue:

![restart browser](https://user-images.githubusercontent.com/26000308/45219258-f8080c80-b2b2-11e8-99f6-8e36315d8563.gif)

**Comment by jonathanKingston** [comment] 2018-09-07 22:52
This should be resolved in the latest signed issue.

**Closed as completed by jonathanKingston** 2018-09-07 22:52 UTC

**Comment by Softvision-RemusDranca** [comment] 2018-09-10 08:37
I have verified this issue using the latest DNS Over HTTPS V4 (4.0.3-signed) version and the issue is no longer reproducible. Tested on Windows 10 x64, Mac 10.13 and Arch Linux.
