### ISSUE TITLE
The "network.trr.uri" pref automatically changes the previously set URL to “https://dns.cloudflare.com/.well-known/dns" after installing the experiment

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [jonathanKingston/http-dns#23] opened 2018-09-06 13:05 UTC
[Notes]:
- In the 1st version of DNS Over HTTPS shield study, we dropped out the “https://dns.cloudflare.com/.well-known/dns” URL and updated it to "https://mozilla.cloudflare-dns.com/dns-query" ([PHD](https://docs.google.com/document/d/1SaBIFVcfNRJWjm8mUtGLvdXpplAikTyfCBTavA39zoQ/edit?ts=5aa7a09a) for V1)

[Affected versions]:
- Firefox DevEdition 63.0b3
- DNS Over HTTPS V4 

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- "network.trr.uri" pref is set to "https://mozilla.cloudflare-dns.com/dns-query"
- DNS Over HTTPS V4 .zip is available ([link](https://github.com/jonathanKingston/http-dns/pull/21)). 

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to "about:debugging" page and install DNS Over HTTPS V4 as a temporary add-on.
3. Go back to "about:config" and observe the "network.trr.uri" pref value.

[Expected result]:
- "https://mozilla.cloudflare-dns.com/dns-query" remains set.

[Actual result]:
- “https://dns.cloudflare.com/.well-known/dns” is displayed.

[Additional Notes]:
- Added a screen recording with the issue:

![url changed](https://user-images.githubusercontent.com/26000308/45159450-7307ef00-b1ef-11e8-945c-c7b86ddc47b0.gif)

**Comment by jonathanKingston** [comment] 2018-09-06 14:22
Fixed in the latest version

**Closed as completed by jonathanKingston** 2018-09-06 14:22 UTC

**Comment by Softvision-RemusDranca** [comment] 2018-09-07 12:46
I have verified this issue using the latest DNS Over HTTPS V4 (4.0.1-signed) version and the issue is no longer reproducible. Tested on Windows 10 x64, Mac 10.13 and Arch Linux.
